### ISSUE TITLE
What black magic is this!?!

### ISSUE THREAD

**Issue by Gronis** [GValiente/gba-niccc#1]
How is this black magic done? I've seen some impressive 3D stuff done on the gba, but not at 60fps with native (not half) resolution, and you are claiming there is at least 40% performance still left on the table, incredible! Is there a technical document on how this is done? Too my knowledge, 30fps at half resolution seems to be pretty common on gba when doing 3D. What is the secret here?

Thanks for this great port!

Feel free to close this issue. I'm just very impressed :)

**Comment by GValiente** [comment]
The trick is in using sprites to render horizontal lines, so it is somewhat hardware accelerated. You can read the source code for the rest :)

Ah, and most commercial GBA 3D games run at 20FPS max, not 30 ;)
